# Generated by Django 5.1.3 on 2024-11-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCLDataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('SOL', 'Solana')], max_length=3)),
                ('interval', models.CharField(choices=[('5m', '5 minutes'), ('15m', '15 minutes'), ('30m', '30 minutes'), ('1h', '1 hour'), ('4h', '4 hours')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'OCL Data Import',
                'verbose_name_plural': 'OCL Data Imports',
            },
        ),
        migrations.CreateModel(
            name='OCLPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'verbose_name': 'OCL Price',
                'verbose_name_plural': 'OCL Prices',
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='BTCPrice',
        ),
        migrations.AddIndex(
            model_name='ocldataimport',
            index=models.Index(fields=['created_at'], name='data_ocldat_created_360db8_idx'),
        ),
        migrations.AddIndex(
            model_name='ocldataimport',
            index=models.Index(fields=['asset', 'interval', 'start_date', 'end_date'], name='data_ocldat_asset_0f1eae_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocldataimport',
            constraint=models.UniqueConstraint(fields=('asset', 'interval', 'start_date', 'end_date'), name='unique_data_import'),
        ),
        migrations.AddField(
            model_name='oclprice',
            name='data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ocldataimport'),
        ),
        migrations.AddIndex(
            model_name='oclprice',
            index=models.Index(fields=['date'], name='data_oclpri_date_e68ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='oclprice',
            index=models.Index(fields=['data_import', 'date'], name='data_oclpri_data_im_6792db_idx'),
        ),
    ]
