# Generated by Django 5.1.3 on 2024-11-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_ocldataimport_oclprice_delete_btcprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocldataimport',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ocldataimport',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ocldataimport',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ocldataimport',
            name='start_date',
            field=models.DateField(),
        ),
    ]
