# Generated by Django 5.1.3 on 2024-11-23 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("strategies", "0002_rating_strategy_user_ratings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="user_ratings",
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
