# Generated by Django 5.1.3 on 2024-11-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("strategies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestPerformingAlgo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algo_return", models.FloatField()),
                ("algo_win_rate", models.FloatField()),
                ("algo_sharpe_ratio", models.FloatField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_performances",
                        to="strategies.strategy",
                    ),
                ),
            ],
        ),
    ]
