# Generated by Django 5.1.3 on 2024-11-23 04:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestperformingalgo",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
