# Generated by Django 5.1.3 on 2024-11-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backtesting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="algo_return",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="algo_sharpe_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backtestresult",
            name="algo_win_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
