# Generated by Django 5.1.3 on 2024-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0002_backtestresult_algo_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='timeframe',
            field=models.CharField(choices=[('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day')], default='4h', max_length=3),
        ),
    ]
