# Generated by Django 5.1.3 on 2024-11-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0003_backtestresult_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backtestresult',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
