# Generated by Django 5.1.3 on 2024-11-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0005_backtestresult_strategy_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
