# Generated by Django 5.1.3 on 2024-11-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0006_backtestresult_end_date_backtestresult_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='leverage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='slippage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
