# Generated by Django 5.1.3 on 2024-11-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0007_backtestresult_commission_backtestresult_leverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='ocl_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='trade_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
