# Generated by Django 5.1.3 on 2024-11-26 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0008_backtestresult_ocl_data_backtestresult_trade_data'),
        ('data', '0002_ocldataimport_oclprice_delete_btcprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backtestresult',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='ocl_data',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='backtestresult',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='ocl_data_import',
            field=models.ForeignKey(blank=True, help_text='OCL data import. Visit the Data page to import data.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.ocldataimport'),
        ),
    ]
