# Generated by Django 5.1.3 on 2024-11-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0009_remove_backtestresult_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='portfolio_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
