# Generated by Django 5.1.3 on 2024-11-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0011_backtestresult_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='ocl_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
